on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: auto release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Hello world action step
        id: hello
        uses: zomint/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Mona the Octocat'
          tag: 'main'
